# Generated by Django 2.2.4 on 2020-05-15 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_car',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=None, to='app01.Book')),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
