# Generated by Django 2.2.4 on 2020-05-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_shopping_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '正常销售'), (1, '已售罄'), (2, '已下架'), (3, '暂时无货')], default=0, verbose_name='状态')),
                ('book_count', models.IntegerField(null=True, verbose_name='在售书籍数量')),
                ('sell_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Book')),
            ],
        ),
    ]
